-- 코드를 입력하세요
SELECT a.MEMBER_ID, a.MEMBER_NAME, a.GENDER, DATE_FORMAT(a.DATE_OF_BIRTH,'%Y-%m-%d') AS 'DATE_OF_BIRTH'
  FROM MEMBER_PROFILE a
 WHERE DATE_FORMAT(a.DATE_OF_BIRTH,'%m') = 3
   AND a.GENDER = 'W'
   AND a.TLNO IS NOT NULL
 ORDER BY a.MEMBER_ID