-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * b.AMOUNT) AS 'TOTAL_SALES'
  FROM FOOD_PRODUCT a LEFT JOIN FOOD_ORDER b
                             ON a.PRODUCT_ID = b.PRODUCT_ID
 WHERE DATE_FORMAT(b.PRODUCE_DATE,'%Y-%m') = '2022-05' 
 GROUP BY a.PRODUCT_ID
 ORDER BY TOTAL_SALES desc, a.PRODUCT_ID