-- 코드를 입력하세요
SELECT DATE_FORMAT(a.SALES_DATE,'%Y') AS YEAR,
       DATE_FORMAT(a.SALES_DATE,'%m') AS MONTH,
       b.GENDER AS GENDER, 
       COUNT(DISTINCT a.USER_ID) AS USERS
  FROM ONLINE_SALE a LEFT JOIN USER_INFO b
                            ON b.USER_ID = a.USER_ID
 WHERE b.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR asc, MONTH asc, GENDER asc