-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(a.PRICE * b.SALES_AMOUNT) as 'SALES'
  FROM PRODUCT a INNER JOIN OFFLINE_SALE b
                        ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES desc, a.PRODUCT_CODE