-- 코드를 입력하세요
SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) as 'TOTAL_ORDER'
  FROM FIRST_HALF a LEFT JOIN ICECREAM_INFO b
                           ON b.FLAVOR = a.FLAVOR
 GROUP BY b.INGREDIENT_TYPE
 ORDER BY 'TOTAL_ORDER'