-- 코드를 입력하세요
SELECT DATE_FORMAT(a.DATETIME,'%H') as 'HOUR', COUNT(DATE_FORMAT(a.DATETIME,'%H')) as 'COUNT'
  FROM ANIMAL_OUTS a
 WHERE DATE_FORMAT(a.DATETIME,'%H:%i') BETWEEN '09:00' and '19:59'
 GROUP BY DATE_FORMAT(a.DATETIME,'%H')
 ORDER BY DATE_FORMAT(a.DATETIME,'%H')