-- 코드를 입력하세요
SELECT a.CAR_ID,
       CASE WHEN b.CAR_ID IS NOT NULL THEN '대여중'
            ELSE '대여 가능' END AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a LEFT JOIN (
      SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
                                                    ) b ON b.CAR_ID = a.CAR_ID
 GROUP BY a.CAR_ID
 ORDER BY a.CAR_ID desc
 