-- 코드를 입력하세요
SELECT a.CAR_TYPE, COUNT(a.CAR_ID) AS CARS
  FROM CAR_RENTAL_COMPANY_CAR a
 WHERE a.OPTIONS LIKE '%통풍시트%'
    OR a.OPTIONS LIKE '%열선시트%'
    OR a.OPTIONS LIKE '%가죽시트%'
GROUP BY a.CAR_TYPE
ORDER BY a.CAR_TYPE

