-- 코드를 입력하세요
SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(a.PUBLISHED_DATE,'%Y-%m-%d') as 'PUBLISH_DATE'
  FROM BOOK a LEFT JOIN AUTHOR b
                     ON b.AUTHOR_ID = a.AUTHOR_ID
 WHERE a.CATEGORY = '경제'
 ORDER BY a.PUBLISHED_DATE 