-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME, SUM(a.PRICE) AS 'TOTAL_SALES'
  FROM USED_GOODS_BOARD a LEFT JOIN USED_GOODS_USER b
                                 ON b.USER_ID = a.WRITER_ID
 WHERE a.STATUS = 'DONE'
 GROUP BY a.WRITER_ID
 HAVING SUM(a.PRICE) >= 700000
 ORDER BY SUM(a.PRICE) asc