-- 코드를 입력하세요
SELECT a.TITLE
     , a.BOARD_ID
     , b.REPLY_ID
     , b.WRITER_ID
     , b.CONTENTS
     , DATE_FORMAT(b.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
  FROM USED_GOODS_BOARD a LEFT JOIN USED_GOODS_REPLY b
                                 ON b.BOARD_ID = a.BOARD_ID
 WHERE a.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
   AND b.REPLY_ID IS NOT NULL
 ORDER BY CREATED_DATE, TITLE