-- 코드를 입력하세요
SELECT a.MCDP_CD as '진료과코드', COUNT(a.APNT_NO) as '5월예약건수'
  FROM APPOINTMENT a
 WHERE DATE_FORMAT(a.APNT_YMD,'%Y-%m') = '2022-05' 
 GROUP BY a.MCDP_CD
 ORDER BY COUNT(a.APNT_NO), a.MCDP_CD 