-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) as 'TOTAL_SALES'
  FROM BOOK a LEFT JOIN BOOK_SALES b
                     ON b.BOOK_ID = a.BOOK_ID
 WHERE LEFT(b.SALES_DATE,7) = '2022-01'
 GROUP BY a.CATEGORY
 ORDER BY a.CATEGORY